#! /bin/bash

# This script is based on the script from following link:
# http://www.uluga.ubuntuforums.org/showthread.php?t=1368224

# Playlist for Daum Search Screensaver
playlist=/usr/share/daum-search-screensaver/playlist

## setup MPlayer aruments, remove -nosound if you want the video
## to play sound. If you have to specify the video driver to use
## then add that to the list
MPLAYERARGS="-nosound -nolirc -wid $XSCREENSAVER_WINDOW -nostop-xscreensaver -fs -really-quiet"

exec mplayer $MPLAYERARGS -loop 0 -shuffle -playlist $playlist
